const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const outDir = path.join(rootDir, 'dist');
const srcHtmlPath = path.join(rootDir, 'src', 'form-generator.html');

if (!fs.existsSync(srcHtmlPath)) {
  console.error('Source form-generator.html not found at', srcHtmlPath);
  process.exit(1);
}

const srcHtml = fs.readFileSync(srcHtmlPath, 'utf8');

// 1. Copy the canonical single-file app into dist/ so it can be opened directly,
//    and as dist/index.html so a static host (GitHub Pages) serves it at the root.
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'form-generator.html'), srcHtml, 'utf8');
fs.writeFileSync(path.join(outDir, 'index.html'), srcHtml, 'utf8');
fs.writeFileSync(path.join(outDir, '.nojekyll'), '', 'utf8');
console.log('Copied', srcHtmlPath, '-> dist/form-generator.html + dist/index.html');

// 2. Emit src/embedded-html.js so `src/index.js` can ship the *real* runtime
//    (mount() renders this, not a stub). Committed to the repo so the package
//    builds even before `build:html` runs, and regenerated here on every build.
const embeddedPath = path.join(rootDir, 'src', 'embedded-html.js');
const banner =
  '// AUTO-GENERATED by scripts/generate-html.js from src/form-generator.html.\n' +
  '// Do not edit by hand; run `npm run build:html`.\n';
fs.writeFileSync(embeddedPath, banner + 'module.exports = ' + JSON.stringify(srcHtml) + ';\n', 'utf8');
console.log('Wrote', embeddedPath, `(${srcHtml.length} bytes embedded)`);
